export type StoryChapter = { id: string; era: string; label: string; title: string; text: string; detail: string; tags: string[]; kind: "portrait" | "experience" | "coach" | "health" | "skill" | "archive"; href: string; action: string; status: string };
export const storyChapters: StoryChapter[] = [
  { id: "present", era: "序", label: "此刻的我", title: "陈俊呈", text: "带着项目协调的经验，走进 AI 产品的世界。", detail: "2025 年本科毕业于大连工业大学，已取得 PMP 认证。现在全职转型 AI 产品，杭州优先、苏州备选。这里既是我的作品集，也是持续续写的人生档案。", tags: ["AI 应用产品方向", "开放工作机会"], kind: "portrait", href: "/resume", action: "阅读我的简历", status: "个人介绍" },
  { id: "exploration", era: "大学—2025", label: "探索与表达", title: "从表达自己，\n到观察世界。", text: "表演专业、时装周、服装设计，以及小规模的内容与商业尝试。", detail: "在校期间参加过时装周模特工作，学习服装设计并完成成衣；有心理学学习及考研经历，也尝试过 TikTok、小红书和私域运营。它们属于个人探索，不是正式互联网工作经历。", tags: ["表演专业", "审美与内容", "个人尝试"], kind: "experience", href: "/resume", action: "查看教育与经历", status: "已发生 · 本人自述" },
  { id: "career", era: "2025—2026", label: "第一段职场", title: "把一件复杂的事，\n一步步推进。", text: "约一年半助理工作，让我接触真实的用户、协作和问题。", detail: "以院长助理为主要身份，承担跨部门协调、任务推进和咨询协作；期间短暂参与代理院长事务，后参与董事长与咨询师支持。曾协调一项匿名退费任务，在一天内完成。2026 年 7 月离职。", tags: ["跨部门协调", "任务推进", "PMP"], kind: "experience", href: "/resume", action: "阅读工作经历", status: "已发生 · 案例匿名" },
  { id: "aipm", era: "2026 · 转型", label: "AI 学习系统", title: "不只知道学什么，\n还要亲手做一遍。", text: "以自己为首位用户，把零散任务变成引导式学习的产品探索。", detail: "我提出讲解、举例、练习与反馈的需求，并持续指出 AI 对话跑偏和操作不清楚的问题。文档与代码由 AI 辅助；教学效果和外部用户体验仍需实际验证。", tags: ["主项目", "AI 应用", "自用迭代"], kind: "coach", href: "/work/aipm-coach", action: "展开学习系统案例", status: "进行中 · 待外部验证" },
  { id: "fitness", era: "2026 · 实践", label: "健身与减脂", title: "从忘记第几组，\n找到一个小问题。", text: "少一点操作和分心，把注意力留给训练。", detail: "我通常完成 4 组，忘记时曾统一当作第 3 组。先探索手动计组、休息计时与撤销，再考虑饮食记录与健康管理；自动识别、手环连接和商业化仍是待验证的方向。", tags: ["真实使用场景", "计组原型", "健康工具"], kind: "health", href: "/work/fitness-companion", action: "展开健身项目案例", status: "原型探索 · 待场景验证" },
  { id: "skill", era: "2026 · 沉淀", label: "复盘 Skill", title: "说清做过什么，\n也说清什么没做。", text: "把零散记录整理成有来源、可核对的项目讲述。", detail: "我选择项目复盘作为第一个 Skill 场景，明确先了解制作过程、完成原型。AI 辅助起草规则与文档，把个人贡献、AI 辅助和未知结果分开。当前尚未完成系统性效果评测。", tags: ["小型案例", "AI 工作流", "证据边界"], kind: "skill", href: "/work/project-retrospective", action: "展开 Skill 制作过程", status: "v0.1 原型 · 待评测" },
  { id: "archive", era: "2026—以后", label: "继续续写", title: "这一卷没有结尾，\n只有下一页。", text: "让每一次真实的经历，都能找到自己的位置。", detail: "这个网站先服务当下求职，往后再逐步收录工作、项目、生活与判断的变化。未来的经历只在实际发生后追加；当前是可交互的框架，不是已经完成的内容管理平台。", tags: ["本网站", "持续迭代", "未来留白"], kind: "archive", href: "/work/personal-archive", action: "查看网站的制作思路", status: "持续记录 · 不预写结局" },
];
